Get_Filename_Component (INSTALL_PREFIX_Debug
  ${CMAKE_BINARY_DIR}/StageArea/Debug ABSOLUTE CACHE)

Get_Filename_Component (INSTALL_PREFIX_Release
  ${CMAKE_BINARY_DIR}/StageArea/Release ABSOLUTE CACHE)

Set (CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${INSTALL_PREFIX_Debug}/bin)
Set (CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${INSTALL_PREFIX_Debug}/lib)
Set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${INSTALL_PREFIX_Debug}/lib/static)

Set (CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${INSTALL_PREFIX_Release}/bin)
Set (CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${INSTALL_PREFIX_Release}/lib)
Set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${INSTALL_PREFIX_Release}/lib/static)

Mark_As_Advanced (
  INSTALL_PREFIX_Debug
  INSTALL_PREFIX_Release
  )

If (CMAKE_BUILD_TYPE)
  String (TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_U)
Else (CMAKE_BUILD_TYPE)
  Set (CMAKE_BUILD_TYPE_U "UNDEFINED-BUILD-TYPE")
EndIf (CMAKE_BUILD_TYPE)
