Set (
  XQILLA_SEARCH_PATHS
  $ENV{XQILLA_DIR}
  $ENV{PACKAGES_DIR}
  )

If (UNIX)
  List (
    APPEND XQILLA_SEARCH_PATHS
    /usr/local
    /usr
    )
EndIf (UNIX)

Find_Program (
  XQILLA_EXECUTABLE
  xqilla
  PATHS ${XQILLA_SEARCH_PATHS}
  PATH_SUFFIXES bin
)

Set (XQILLA_INC_SEARCH_PATHS)

If (XQILLA_EXECUTABLE)
  Get_Filename_Component (XQILLA_BIN_DIR ${XQILLA_EXECUTABLE} PATH CACHE)
  Get_Filename_Component (XQILLA_ROOT_DIR ${XQILLA_BIN_DIR} PATH CACHE)
  List (
    APPEND XQILLA_INC_SEARCH_PATHS
    ${XQILLA_ROOT_DIR}
    )
EndIf (XQILLA_EXECUTABLE)

Find_File (
  XQILLA_INC_HEADER
  xqc.h
  PATHS ${XQILLA_INC_SEARCH_PATHS}
  PATH_SUFFIXES include
  )

If (XQILLA_INC_HEADER)
  Get_Filename_Component (XQILLA_INCLUDE_DIR ${XQILLA_INC_HEADER} PATH CACHE)

  If (NOT XQILLA_ROOT_DIR)
    Get_Filename_Component (XQILLA_ROOT_DIR ${XQILLA_INCLUDE_DIR} PATH CACHE)
  EndIf (NOT XQILLA_ROOT_DIR)

  Find_Library (
    XQILLA_OPTIMIZED_LIBRARY
    xqilla
    PATHS ${XQILLA_ROOT_DIR}
    PATH_SUFFIXES lib
    )

  Find_Library (
    XQILLA_DEBUG_LIBRARY
    NAMES xqillad xqilla
    PATHS ${XQILLA_ROOT_DIR}
    PATH_SUFFIXES lib-debug lib
    NO_DEFAULT_PATH
    )
EndIf (XQILLA_INC_HEADER)

If (XQILLA_DEBUG_LIBRARY AND XQILLA_OPTIMIZED_LIBRARY)
  Set (
    XQILLA_LIBRARIES 
    optimized ${XQILLA_OPTIMIZED_LIBRARY}
    debug ${XQILLA_DEBUG_LIBRARY}
    )
ElseIf (XQILLA_DEBUG_LIBRARY)
  Set (XQILLA_LIBRARIES ${XQILLA_DEBUG_LIBRARY})
ElseIf (XQILLA_OPTIMIZED_LIBRARY)
  Set (XQILLA_LIBRARIES ${XQILLA_OPTIMIZED_LIBRARY})
EndIf (XQILLA_DEBUG_LIBRARY AND XQILLA_OPTIMIZED_LIBRARY)

Set (XQILLA_Debug_LIBRARY ${XQILLA_DEBUG_LIBRARY})
Set (XQILLA_Release_LIBRARY ${XQILLA_OPTIMIZED_LIBRARY})

Mark_As_Advanced (
  XQILLA_EXECUTABLE
  XQILLA_INCLUDE_DIR
  XQILLA_OPTIMIZED_LIBRARY
  XQILLA_DEBUG_LIBRARY
  XQILLA_INC_HEADER
  XQILLA_ROOT_DIR
  XQILLA_LIBRARIES
  )
