Include (${CMAKE_MODULE_PATH}/Xerces.cmake)

Find_Libraries (
  ZORBA
  EXECUTABLE zorba
  HEADER xqc.h
  LIBRARY zorba_simplestore
  )

#If (ZORBA_EXECUTABLE)
#  Execute_Process (
#    COMMAND ${ZORBA_EXECUTABLE} "--version"
#    RESULT_VARIABLE ZORBA_VERSION_RESULT
#    OUTPUT_VARIABLE ZORBA_VERSION_OUTPUT
#    ERROR_VARIABLE ZORBA_VERSION_ERROR
#    OUTPUT_STRIP_TRAILING_WHITESPACE
#    )
#
#  If (NOT ZORBA_VERSION_RESULT)
#    Message (${ZORBA_VERSION_ERROR})
#  Else (NOT ZORBA_VERSION_RESULT)
#    String (REPLACE "Zorba XQuery Engine, Version: " "" ZORBA_VERSION ${ZORBA_VERSION_OUTPUT})
#  EndIf (NOT ZORBA_VERSION_RESULT)
#
#EndIf (ZORBA_EXECUTABLE)
